stages:
  - build
  - test

.deb12: &deb12
  image: debian:bookworm
  before_script:
    - apt update -qq
    - apt install -y cargo

.deb13: &deb13
  image: debian:trixie
  before_script:
    - apt update -qq
    - apt install -y cargo

build-deb12:
  <<: *deb12
  stage: build
  script:
    - cargo test --verbose

unit-test-deb12:
  <<: *deb12
  stage: test
  script:
    - cargo test --verbose

build-deb13:
  <<: *deb13
  stage: build
  script:
    - cargo test --verbose

unit-test-deb13:
  <<: *deb13
  stage: test
  script:
    - cargo test --verbose

