stages:
  - build
  - test

.deb12: &deb12
  image: debian:bookworm
  before_script:
    - apt update -qq
    - apt install -y cargo
  rules:
    - when: never            # debian 12 rust is too old, don't care right now

.deb13: &deb13
  image: debian:trixie
  before_script:
    - apt update -qq
    - apt install -y cargo

build-deb12:
  <<: *deb12
  stage: build
  script:
    - cargo build --verbose

unit-test-deb12:
  <<: *deb12
  stage: test
  needs:
    - job: build-deb12
      artifacts: true
  variables:
      RUST_LOG: trace
  script:
    - cargo test --verbose

build-deb13:
  <<: *deb13
  stage: build
  script:
    - cargo build --verbose

unit-test-deb13:
  <<: *deb13
  stage: test
  needs:
    - job: build-deb13
      artifacts: true
  variables:
      RUST_LOG: trace
  script:
    - cargo test --verbose

