[package]
name = "clinvoice"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
colored = "2.0"
atty = "0.2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
tera = "1"
serde_json = "1.0"
