# this part would usually be a system wide config in $HOME/.clinvoice
[issuer]
    company     = "BURN-E"
    address     = "1 Main Ave | Ottawa, ON, K2C 4E6 | Canada"
    phone       = "613-282-7102"

# and the rest would live in this file (in the project dir)
[client]
    short-name  = "BNL"
    care_of     = "Shelby Forthright"
    company     = "Buy N Large"
    address     = "1 Buy n Large Plaza, BnL Ave. | Largefield, NJ, 08012 | USA"
    phone       = "201-555-0001"

[contract]
    hourly_rate           = 50.0
    payment_days          = 30
    # client will not pay for overtime, monthly hours are capped at 64 hours
    cap_hours_per_day     = 10
    cap_hours_per_invoice = 64

[tax]
    name        = "VAT"
    percent     = 10
    description = "tax number 12345"

[sequence]
    file        = ".sequence"

[generator]
    default     = "pdf"

[generator.latex]
    # template file to read in to generate output
    template    = "bnl-template.tex"
    # some output formats require special escaping
    escape      = "latex"
    # output to generate, with the same substitutions as the template
    output      = 'bnl-{{ period_end | date(format="%Y%m%d") }}-{{ sequence }}.tex'

[generator.txt]
    template    = "bnl-template.txt"
    output      = 'bnl-{{ period_end | date(format="%Y%m%d") }}-{{ sequence }}.txt'

[generator.pdf]
    template    = "bnl-template.tex"
    escape      = "latex"
    output      = 'bnl-{{ period_end | date(format="%Y%m%d") }}-{{ sequence }}.tex'
    # rendering is done by calling this program
    build       = "pdflatex {{ output }}"

